id: P6D608808
initial_creation_type: input
source_metadata:
  title: Madhyamakāvatāra Series
  language: en
  description: 'Texts related to the Madhyamakāvatāra (dbu ma la ’jug pa), or Introduction
    to the Middle Way, by Candrakīrti:'
  volume:
    d5349cbdc9434292b5e6b6b7c426be75:
      title: Commentary on the Madhyamakāvatāra—Part 1—Collection of Reasoning
      parent: Commentary
    61ab3ba820924f6e82faf747a75a1fc2:
      title: Commentary on the Madhyamakāvatāra—Part 2—Title and Translators Homage
      parent: Commentary
    57d8c26501a543409e6aa52833a1adc0:
      title: Prologue to Introduction to the Middle Way (Madhyamakāvatāra)
      parent: Prologue
created_at: '2022-03-01T04:30:16.730847'
last_modified_at: '2022-03-01T04:30:16.730857'
